language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install: 
  - "pip install coverage"
  - "pip install coveralls"
script: 
  - "coverage run --omit=*.virtualenvs*,*virtualenv* setup.py test"
after_success:
    coveralls
